[package]
name = "mustang"
version = "0.1.1-alpha.0"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
]
description = "Rust programs written entirely in Rust"
documentation = "https://docs.rs/mustang"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/sunfishcode/mustang"
edition = "2018"

[build-dependencies]
# Enable the cc dependency to build the empty `libc.a` and similar libraries
# from the empty.s source file, instead of using the prebuilt libraries.
cc = { version = "1.0.68", optional = true }

[dependencies]

[target.'cfg(target_vendor = "mustang")'.dependencies]
origin = { path = "../origin", default-features = false, version = "^0.1.1-alpha.0"}
c-scape = { path = "../c-scape", version = "^0.1.1-alpha.0"}

[features]
default = ["threads"]
threads = ["origin/threads", "c-scape/threads"]
